services:
  web:
    image: codingforentrepreneurs/rk8s-js:${TAG:-latest}
    build: 
      context: .
      dockerfile: Dockerfile
      tags:
        - "codingforentrepreneurs/rk8s-js:${TAG:-latest}"
    ports:
      - "80:3000"
    environment:
      - PORT=3000