---
- name: Deploy Node.js app
  hosts: all
  become: yes
  variables:
    nodejs_version: 18.16.0
  tasks:
    - name: Update and upgrade system
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
    - name: Install dependencies
      apt:
        pkg:
          - curl
          - rsync
          - nginx
          - supervisor
        state: present
      tags: install
    - name: remove system nodejs
      apt:
        pkg: 
          - nodejs
        state: absent
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
    - name: Install node
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ nodejs_version }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ nodejs_version }}"
    - name: Update npm
      shell: |
        export nvm_npm=~/.nvm/versions/node/v{{ nodejs_version }}/bin/npm
        nvm_npm install -g npm@latest
    - name: Echo Node.js Version Installed
      shell: >
        node --version
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
      register: node_version
    - name: Show Node version
      debug:
        msg : "{{ node_version.stdout }}"
    - name: Set up application directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/projects/roadtok8s/js/src/
        - /var/log/supervisor/roadtok8s/js/
    - name: Copy Node.js app to remote server
      synchronize:
        src: '{{ playbook_dir }}/../../src/'
        dest: /opt/projects/roadtok8s/js/src/
        recursive: yes
        delete: yes
    - name: Copy Package.json to remote server
      synchronize:
        src: '{{ playbook_dir }}/../../package.json'
        dest: /opt/projects/roadtok8s/js/package.json
        recursive: yes
        delete: yes
    - name: Install Node.js packages
      shell: |
        cd /opt/projects/roadtok8s/js/ && npm install
      args:
        executable: /bin/bash
    - name: Configure Node.js with supervisor
      copy:
        src: ../../conf/supervisor.conf
        dest: /etc/supervisor/conf.d/roadtok8s-js.conf
    - name: Configure nginx
      copy:
        src: ../../conf/nginx.conf
        dest: /etc/nginx/sites-available/roadtok8s-js
      notify: restart nginx
    - name: Enable nginx site
      command: ln -s /etc/nginx/sites-available/roadtok8s-js /etc/nginx/sites-enabled
      args:
        creates: /etc/nginx/sites-enabled/roadtok8s-js
    - name: Remove default nginx site
      file:
        path: "{{ item }}"
        state: absent
      notify: restart nginx
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
    - name: Update supervisor and start Node.js app
      command: "{{ item }}"
      with_items:
        - supervisorctl reread
        - supervisorctl update
        - supervisorctl restart roadtok8s-js

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
